### ISSUE TITLE
程序运行崩溃

### ISSUE THREAD

**Issue by Greathfs** [xm0625/VBrowser-Android#1]
![image](https://user-images.githubusercontent.com/18097997/32277689-38c6f582-bf4e-11e7-86d6-8f763a2a0b1a.png)

**Comment by xm0625** [comment]
方便提供以下信息吗？

你的手机型号
Android版本
安装的apk文件名

**Comment by Greathfs** [comment]
我用的模拟器 海马玩 Android 4.2版本
我是clone整个项目到本地 运行的 
运行完打开就会报这个错误

**Comment by xm0625** [comment]
尝试拉取最新的代码 重新运行

**Comment by Greathfs** [comment]
还是报这个错误 不知道作者是用的什么机型做测试的

**Comment by Greathfs** [comment]
如果MainActivity继承XWalkActivity也会报错
![image](https://user-images.githubusercontent.com/18097997/33129284-56dc6142-cfca-11e7-9ca6-3b3d01a9e9cc.png)

**Comment by xm0625** [comment]
genymotion和小米5测试都是通过的。没有Windows环境，没有去测海马玩。
目前我猜测的原因是, 海马玩模拟器可能是64位的.目前的ndk的x86库是32位的.
当Crosswalk执行时发现找不到当前架构可用的ndk库文件时, 会以shared模式运行, 该模式下会尝试去寻找本机上是否存在其他Crosswalk应用, 如果存在将会共享Crosswalk核心(类似腾讯X5核心, 它可以共享微信或者QQ的X5浏览核心).
你可以fork此项目让它支持64位的库(Crosswalk有提供64位的arm/x86 ndk库文件)
或者更换虚拟机

**Comment by Greathfs** [comment]
OK 晚上有时间我fork下 改一改
发自网易邮箱大师
在2017年11月23日 17:57，xm0625 写道： genymotion和小米5测试都是通过的。没有Windows环境，没有去测海马玩。
目前我猜测的原因是, 海马玩模拟器可能是64位的.目前的ndk的x86库是32位的.
当Crosswalk执行时发现找不到当前架构可用的ndk库文件时, 会以shared模式运行, 该模式下会尝试去寻找本机上是否存在其他Crosswalk应用, 如果存在将会共享Crosswalk核心(类似腾讯X5核心, 它可以共享微信或者QQ的X5浏览核心).
你可以fork此项目让它支持64位的库(Crosswalk有提供64位的arm/x86 ndk库文件)
或者更换虚拟机

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/xm0625/VBrowser-Android","title":"xm0625/VBrowser-Android","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/xm0625/VBrowser-Android"}},"updates":{"snippets":[{"icon":"PERSON","message":"@xm0625 in #1: genymotion和小米5测试都是通过的。没有Windows环境，没有去测海马玩。\r\n目前我猜测的原因是, 海马玩模拟器可能是64位的.目前的ndk的x86库是32位的.\r\n当Crosswalk执行时发现找不到当前架构可用的ndk库文件时, 会以shared模式运行, 该模式下会尝试去寻找本机上是否存在其他Crosswalk应用, 如果存在将会共享Crosswalk核心(类似腾讯X5核心, 它可以共享微信或者QQ的X5浏览核心).\r\n你可以fork此项目让它支持64位的库(Crosswalk有提供64位的arm/x86 ndk库文件)\r\n或者更换虚拟机\r\n\r\n \r\n"}],"action":{"name":"View Issue","url":"https://github.com/xm0625/VBrowser-Android/issues/1#issuecomment-346573796"}}}

**Comment by xm0625** [comment]
最新版本已经加入了对高版本API设备的支持，加入64位的库文件以对特定架构的CPU进行优化。
尝试下载最新的版本的代码编译或直接下载release v1.2的安装包重新尝试一下。
