### ISSUE TITLE
没有缓存完成的视频，再打开就消失了

### ISSUE THREAD

**Issue by Sohnia** [xm0625/VBrowser-Android#14]
问题出现，Android 8.0 华为play

**Comment by xm0625** [comment]
下载未完成是不能退出的哦

**Comment by xm0625** [comment]
home键切换到后台运行没关系

**Comment by Sohnia** [comment]
短点续传至少得要啊。
或者后台一个service也行啊。

**Comment by Sohnia** [comment]
这是一个严重的bug

**Comment by xm0625** [comment]
后台service是有的。可以看通知栏，有一个前台运行的Service附带的通知栏提示。看看是不是一退到后台Service就被干掉了呢？

**Comment by Sohnia** [comment]
我明天研究研究你的代码
