### ISSUE TITLE
使用自带webView可以吗

### ISSUE THREAD

**Issue by marscl** [xm0625/VBrowser-Android#2]
这个太大了

**Comment by xm0625** [comment]
一开始的设计是基于WebView的，但是WebView存在一些问题，比如隐晦的生命周期，糟糕的内存管理以及Android阵营碎片化导致的一些奇奇怪怪的h5支持问题，导致我在Alpha版发布之前就弃用了WebView并转到CrossWalk浏览核心。
可以更改app/build.gradle中的NDK的配置，目前包括了armv7和X86，如果是手机用，可以只打包armv7,去掉x86。
